### ISSUE TITLE
Terminate called when aligning overlaps

### ISSUE THREAD

**Issue by hugocarmaga** [rlorigro/GetBlunted#35]
Hi!

So, I'm trying to use your tool in my analysis, but for the graphs I'm using, I get this error with most of them:

```
[get_blunted : 0.0 s elapsed] Reading GFA...
[get_blunted : 0.0 s elapsed] Computing adjacency components...
[get_blunted : 0.0 s elapsed] Total adjacency components: 4
[get_blunted : 0.0 s elapsed] Computing biclique covers...
[get_blunted : 0.0 s elapsed] Duplicating node termini...
[get_blunted : 0.0 s elapsed] Harmonizing biclique edge orientations...
[get_blunted : 0.0 s elapsed] Aligning overlaps...
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::at: __n (which is 4) >= this->size() (which is 4)
Aborted
```

I've used graphs generated with both Hifiasm and MBG, and the error persists. To try a diagnose for the problem, I've generated two test case graphs.

The first one was like this:
```
S       node1   AAAAAACCCAAAAAAAAAAAAAAAAAAAAA
S       node2   TTTTTTGGGGGGGGGGGGGGGGGGGGGGGG
L       node1   -       node2   +       6M
```
So, with this one, the bluntification was successful and the output was according to what was expected. But then I added a third node and made this graph:
```
S       node1   AAAAAACCCAAAAAAAAAAAAAAAAAAAAA
S       node2   TTTTTTGGGGGGGGGGGGGGGGGGGGGGGG
S       node3   AAAA
L       node1   -       node2   +       6M
L       node1   -       node3   +       4M
L       node2   -       node3   +       4M
```
With this one, I got the aforementioned error. Based on this, I think the error might be associated with overlaps the same size or bigger than the nodes. Are you aware of this? Is that what's causing the error? Do you have any solution for this?

Thanks!
Hugo

**Comment by rlorigro** [comment]
Hi, 

Thank you for the minimal reproducing example. I will take a look today. The case where the node is fully overlapped is intended to be handled, but the case where the overlap is longer than the node is not. If the overlap is longer than the node then it describes an impossible alignment, and it indicates the GFA is wrong.

The author of Hifiasm chose to use "M" operations arbitrarily to represent the length of the longest read involved in the overlap. So there is no way to know how much overlapping sequence there actually is, and for that reason GetBlunted is not suitable for Hifiasm GFAs unfortunately. I have discussed this with the author and he indicated that he would fix it in v0.14, but that was nearly a year ago, so you may want to open an issue on their github page to bring it up again. Additionally, their overlaps are many kilobases in length, which would make realignment using POA very slow.
